### PR TITLE
Moving to main zally repository

### LINKED ISSUE #16: Move to Zally Core Repository
Related to / triggered by https://github.com/zalando-incubator/zally/issues/461

### PR DESCRIPTION
**Pull request by maxim-tschumak**
Closes #16.

### CODE REVIEW

**Comment by netme** [comment]
👍 

Could you please also disable Travis and Zappr on it?

**Comment by maxim-tschumak** [comment]
Forgot to remove the hidden files.. Thanks! Please re-approve :)

**Comment by netme** [comment]
👍

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by maxim-tschumak** [comment]
@netme Are you a admin of this repo? (I'm not, and cannot deactivate Travic)

**Comment by netme** [comment]
@maxim-tschumak unfortunately not. Maybe @rbarilani can help us here?

**Comment by rbarilani** [comment]
@maxim-tschumak @netme done. sorry for the delay.

**Comment by netme** [comment]
Thanks @rbarilani !

**Comment by netme** [comment]
I will reopen this PR

**Pull request closed without merging**
